import './globals.css';
import Link from 'next/link';

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <h1
                    style={{
                        display: 'flex',
                        justifyContent: 'center',
                        color: '#4884cd',
                    }}>
                    Testing
                </h1>
                <Link href="/">Home</Link>
                <Link href="/pokemons">Pokemons</Link>
                {children}
            </body>
        </html>
    );
}
